In [241]:
from google.colab import drive, files
drive.mount('/content/gdrive/')

import os
PROJECT_FOLDER = "/content/gdrive/MyDrive/Colab Notebooks/Thesis"
os.chdir(PROJECT_FOLDER)
print("Current dir: ", os.getcwd())

Drive already mounted at /content/gdrive/; to attempt to forcibly remount, call drive.mount("/content/gdrive/", force_remount=True).
Current dir:  /content/gdrive/MyDrive/Colab Notebooks/Thesis

In [276]:
import pandas as pd

historical_data = pd.read_csv("AMZN_HISTORICAL_DATA.csv")
historical_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-05-10 00:00:00-04:00,164.115997,164.149994,159.500000,159.524506,116772000,0.0,0.0
1,2021-05-11 00:00:00-04:00,156.813995,161.899994,156.368500,161.195496,92396000,0.0,0.0
2,2021-05-12 00:00:00-04:00,159.250000,160.397003,156.654999,157.597000,98728000,0.0,0.0
3,2021-05-13 00:00:00-04:00,159.273499,160.192001,156.649994,158.073502,67018000,0.0,0.0
4,2021-05-14 00:00:00-04:00,159.278000,161.442993,159.149994,161.145004,66500000,0.0,0.0

In [277]:
news_articles = pd.read_csv("AMAZON_NEWS_HEADLINES_FINAL.csv")
news_articles.head()
print(len(news_articles.index))

9529

In [278]:
news_articles = news_articles.rename(columns={"0":"article-title"})
news_articles.head()

                                                                                                                                                                                                                                          article-title
0  5 big analyst AI moves: Microsoft downgraded; Time to revisit AI trade, WF says\nInvesting.com -- Here are the biggest analyst moves in the area of artificial intelligence (AI) for this week. InvestingPro...\nByInvesting.com\n•5 hours ago\n•\n2
1                                                Investing.com’s stocks of the week\nInvesting.com --  Market sentiment was given somewhat of a boost this week with the U.S. and U.K. announcing a trade deal...\nByInvesting.com\n•May 10, 2025\n•\n4
2                       Eleven soldiers killed in Ecuador after clash with criminal group\nQUITO (Reuters) -Eleven soldiers were killed and one was injured in Ecuador’s Amazon (NASDAQ:AMZN) region during an armed...\nByReuters\n•May 09, 2025\n•\n5
3                          US Department of Labor closes investigation into Scale AI\n(Reuters) - The U.S. Department of Labor has closed its investigation into Scale AI’s compliance with the Fair Labor Standards...\nByReuters\n•May 09, 2025\n•\n1
4     Container shipping firms cull Asia-US service as Trump tariffs collapse trade\nBy Lisa Baertlein LOS ANGELES (Reuters) -Major container shipping companies are suspending at least six scheduled weekly routes...\nByReuters\n•May 09, 2025\n•\n1

In [279]:
news_articles["article-title"] = news_articles["article-title"].str.split('•')

In [280]:
news_articles.head()

                                                                                                                                                                                                                                              article-title
0  [5 big analyst AI moves: Microsoft downgraded; Time to revisit AI trade, WF says\nInvesting.com -- Here are the biggest analyst moves in the area of artificial intelligence (AI) for this week. InvestingPro...\nByInvesting.com\n, 5 hours ago\n, \n2]
1                                                [Investing.com’s stocks of the week\nInvesting.com --  Market sentiment was given somewhat of a boost this week with the U.S. and U.K. announcing a trade deal...\nByInvesting.com\n, May 10, 2025\n, \n4]
2                       [Eleven soldiers killed in Ecuador after clash with criminal group\nQUITO (Reuters) -Eleven soldiers were killed and one was injured in Ecuador’s Amazon (NASDAQ:AMZN) region during an armed...\nByReuters\n, May 09, 2025\n, \n5]
3                          [US Department of Labor closes investigation into Scale AI\n(Reuters) - The U.S. Department of Labor has closed its investigation into Scale AI’s compliance with the Fair Labor Standards...\nByReuters\n, May 09, 2025\n, \n1]
4     [Container shipping firms cull Asia-US service as Trump tariffs collapse trade\nBy Lisa Baertlein LOS ANGELES (Reuters) -Major container shipping companies are suspending at least six scheduled weekly routes...\nByReuters\n, May 09, 2025\n, \n1]

In [281]:
news_articles['article-title'] = news_articles['article-title'].astype(str)
news_articles['article-title'] = news_articles['article-title'].str.replace('[', '', regex = False).str.replace(']', '', regex = False)

In [282]:
news_articles["article-title"] = news_articles['article-title'].str.replace(r"\n", "")
news_articles.head(10)

                                                                                                                                                                                                                                        article-title
0  '5 big analyst AI moves: Microsoft downgraded; Time to revisit AI trade, WF saysInvesting.com -- Here are the biggest analyst moves in the area of artificial intelligence (AI) for this week. InvestingPro...ByInvesting.com', '5 hours ago', '2'
1                                                'Investing.com’s stocks of the weekInvesting.com --  Market sentiment was given somewhat of a boost this week with the U.S. and U.K. announcing a trade deal...ByInvesting.com', 'May 10, 2025', '4'
2                       'Eleven soldiers killed in Ecuador after clash with criminal groupQUITO (Reuters) -Eleven soldiers were killed and one was injured in Ecuador’s Amazon (NASDAQ:AMZN) region during an armed...ByReuters', 'May 09, 2025', '5'
3                          'US Department of Labor closes investigation into Scale AI(Reuters) - The U.S. Department of Labor has closed its investigation into Scale AI’s compliance with the Fair Labor Standards...ByReuters', 'May 09, 2025', '1'
4     'Container shipping firms cull Asia-US service as Trump tariffs collapse tradeBy Lisa Baertlein LOS ANGELES (Reuters) -Major container shipping companies are suspending at least six scheduled weekly routes...ByReuters', 'May 09, 2025', '1'
5              'Brazil, China discuss railway from Peruvian port to Brazil territoryBRASILIA (Reuters) - Brazil is in talks with China to build a railway connecting the Chinese-built mega Chancay port in Peru to...ByReuters', 'May 09, 2025', '1'
6                                            'Morning Bid: Tariff rollback hopes risingBy Mike Dolan LONDON (Reuters) - What matters in U.S. and global markets today By Mike Dolan, Editor-At-Large, Financial Industry...ByReuters', 'May 09, 2025'
7                                                                                                                                                      'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'
8                                                                                                                                                      'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'
9                                                                                                                                                      'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'

In [283]:
def clean_title(title):
    title = str(title)
    if len(title) >= 5:
      if title[-5] == ',':
        return title[:-5]
    return title

In [284]:
news_articles['article-title'] = news_articles['article-title'].apply(clean_title)

news_articles.head(20)

                                                                                                                                                                                                                                            article-title
0           '5 big analyst AI moves: Microsoft downgraded; Time to revisit AI trade, WF saysInvesting.com -- Here are the biggest analyst moves in the area of artificial intelligence (AI) for this week. InvestingPro...ByInvesting.com', '5 hours ago'
1                                                         'Investing.com’s stocks of the weekInvesting.com --  Market sentiment was given somewhat of a boost this week with the U.S. and U.K. announcing a trade deal...ByInvesting.com', 'May 10, 2025'
2                                'Eleven soldiers killed in Ecuador after clash with criminal groupQUITO (Reuters) -Eleven soldiers were killed and one was injured in Ecuador’s Amazon (NASDAQ:AMZN) region during an armed...ByReuters', 'May 09, 2025'
3                                   'US Department of Labor closes investigation into Scale AI(Reuters) - The U.S. Department of Labor has closed its investigation into Scale AI’s compliance with the Fair Labor Standards...ByReuters', 'May 09, 2025'
4              'Container shipping firms cull Asia-US service as Trump tariffs collapse tradeBy Lisa Baertlein LOS ANGELES (Reuters) -Major container shipping companies are suspending at least six scheduled weekly routes...ByReuters', 'May 09, 2025'
5                       'Brazil, China discuss railway from Peruvian port to Brazil territoryBRASILIA (Reuters) - Brazil is in talks with China to build a railway connecting the Chinese-built mega Chancay port in Peru to...ByReuters', 'May 09, 2025'
6                                                'Morning Bid: Tariff rollback hopes risingBy Mike Dolan LONDON (Reuters) - What matters in U.S. and global markets today By Mike Dolan, Editor-At-Large, Financial Industry...ByReuters', 'May 09, 2025'
7                                                                                                                                                          'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'
8                                                                                                                                                          'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'
9                                                                                                                                                          'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'
10                                                                                                                                                         'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'
11                                                                                                                                                         'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'
12             'Near-record US container import streak expected to snap in May due to tariffsBy Lisa Baertlein and Andrea Shalal LOS ANGELES/WASHINGTON (Reuters) -U.S. container imports surged in April as companies raced...ByReuters', 'May 08, 2025'
13          'Pinterest’s revenue forecast gets boost from AI ad tools, growing marketing spendBy Jaspreet Singh (Reuters) -Pinterest forecast current-quarter revenue above Wall Street estimates on Thursday, signaling its...ByReuters', 'May 08, 2025'
14                         'Amazon partners with Vetsource to offer pet prescriptionsInvesting.com -- Amazon has expanded its pet care range by partnering with Vetsource, a top pet pharmacy, to provide prescription...ByInvesting.com', 'May 08, 2025'
15               'Shopify sees strong revenue as e-commerce business grows despite tariff gloomBy Deborah Mary Sophia (Reuters) - Shopify (NASDAQ:SHOP) is seeing steady growth in the number of merchants signing up on its...ByReuters', 'May 08, 2025'
16                           'Britain’s digital tax on ’Big Tech’ not impacted by trade dealLONDON (Reuters) -Britain’s digital services tax, imposed on U.S. companies like Amazon (NASDAQ:AMZN), Google (NASDAQ:GOOGL) and...ByReuters', 'May 08, 2025'
17                                                                                                                      'The Trade Desk Q1 preview: Here’s why RBC Capital Markets analysts are expecting a ‘solid start’ByInvesting.com', 'May 08, 2025'
18  'Mega-cap tech names seem to be less impacted by tariffs than S&P peers - JefferiesInvesting.com - Aggressive U.S. tariffs have seemed to hurt the so-called "Magnificent Seven" mega-cap tech companies less than...ByInvesting.com', 'May 08, 2025'
19                                                                                                                                                                'Carvana receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 08, 2025'

In [285]:
news_articles['article-date'] = news_articles['article-title'].str[-13:-1]
news_articles.head(50)

,article-title,article-date
0,"'5 big analyst AI moves: Microsoft downgraded; Time to revisit AI trade, WF saysInvesting.com -- Here are the biggest analyst moves in the area of artificial intelligence (AI) for this week. InvestingPro...ByInvesting.com', '5 hours ago'",'5 hours ago
1,"'Investing.com’s stocks of the weekInvesting.com -- Market sentiment was given somewhat of a boost this week with the U.S. and U.K. announcing a trade deal...ByInvesting.com', 'May 10, 2025'","May 10, 2025"
2,"'Eleven soldiers killed in Ecuador after clash with criminal groupQUITO (Reuters) -Eleven soldiers were killed and one was injured in Ecuador’s Amazon (NASDAQ:AMZN) region during an armed...ByReuters', 'May 09, 2025'","May 09, 2025"
3,"'US Department of Labor closes investigation into Scale AI(Reuters) - The U.S. Department of Labor has closed its investigation into Scale AI’s compliance with the Fair Labor Standards...ByReuters', 'May 09, 2025'","May 09, 2025"
4,"'Container shipping firms cull Asia-US service as Trump tariffs collapse tradeBy Lisa Baertlein LOS ANGELES (Reuters) -Major container shipping companies are suspending at least six scheduled weekly routes...ByReuters', 'May 09, 2025'","May 09, 2025"
5,"'Brazil, China discuss railway from Peruvian port to Brazil territoryBRASILIA (Reuters) - Brazil is in talks with China to build a railway connecting the Chinese-built mega Chancay port in Peru to...ByReuters', 'May 09, 2025'","May 09, 2025"
6,"'Morning Bid: Tariff rollback hopes risingBy Mike Dolan LONDON (Reuters) - What matters in U.S. and global markets today By Mike Dolan, Editor-At-Large, Financial Industry...ByReuters', 'May 09, 2025'","May 09, 2025"
7,"'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'","May 09, 2025"
8,"'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'","May 09, 2025"
9,"'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'","May 09, 2025"
10,"'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'","May 09, 2025"
11,"'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'","May 09, 2025"
12,"'Near-record US container import streak expected to snap in May due to tariffsBy Lisa Baertlein and Andrea Shalal LOS ANGELES/WASHINGTON (Reuters) -U.S. container imports surged in April as companies raced...ByReuters', 'May 08, 2025'","May 08, 2025"
13,"'Pinterest’s revenue forecast gets boost from AI ad tools, growing marketing spendBy Jaspreet Singh (Reuters) -Pinterest forecast current-quarter revenue above Wall Street estimates on Thursday, signaling its...ByReuters', 'May 08, 2025'","May 08, 2025"
14,"'Amazon partners with Vetsource to offer pet prescriptionsInvesting.com -- Amazon has expanded its pet care range by partnering with Vetsource, a top pet pharmacy, to provide prescription...ByInvesting.com', 'May 08, 2025'","May 08, 2025"
15,"'Shopify sees strong revenue as e-commerce business grows despite tariff gloomBy Deborah Mary Sophia (Reuters) - Shopify (NASDAQ:SHOP) is seeing steady growth in the number of merchants signing up on its...ByReuters', 'May 08, 2025'","May 08, 2025"
16,"'Britain’s digital tax on ’Big Tech’ not impacted by trade dealLONDON (Reuters) -Britain’s digital services tax, imposed on U.S. companies like Amazon (NASDAQ:AMZN), Google (NASDAQ:GOOGL) and...ByReuters', 'May 08, 2025'","May 08, 2025"
17,"'The Trade Desk Q1 preview: Here’s why RBC Capital Markets analysts are expecting a ‘solid start’ByInvesting.com', 'May 08, 2025'","May 08, 2025"
18,"'Mega-cap tech names seem to be less impacted by tariffs than S&P peers - JefferiesInvesting.com - Aggressive U.S. tariffs have seemed to hurt the so-called ""Magnificent Seven"" mega-cap tech companies less than...ByInvesting.com', 'May 08, 2025'","May 08, 2025"
19,"'Carvana receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 08, 2025'","May 08, 2025"
20,"'Shopify’s Q1 results expected to beat, but trade policy clouds outlookByInvesting.com', 'May 08, 2025'","May 08, 2025"
21,"'Google cuts about 200 staff in global business unit, The Information reports(Reuters) -Google on Tuesday cut about 200 jobs across its global business unit, which is responsible for sales and partnerships,...ByReuters', 'May 07, 2025'","May 07, 2025"
22,"'Marvell Technology Group Ltd receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 07, 2025'","May 07, 2025"
23,"'Amazon’s 800K stake in AMD realted to ZT acqusitionByInvesting.com', 'May 07, 2025'","May 07, 2025"
24,"'PepsiCo and AWS Collaborate to Accelerate Digital TransformationPepsiCo selects AWS as a strategic cloud provider for AI, supply chain and consumer experience. PURCHASE, N.Y., May 7, 2025...ByInvesting.com', 'May 07, 2025'","May 07, 2025"
25,"'Amazon to spend $4 billion on cloud infrastructure in ChileBy Fabian Cambero SANTIAGO (Reuters) -Amazon’s cloud computing division will invest $4 billion to build its first data centers...ByReuters', 'May 07, 2025'","May 07, 2025"
26,"'Amazon to launch AWS region in Chile, investing $4 billionSEATTLE - Amazon.com Inc. (NASDAQ: AMZN), the prominent broadline retail player with a market capitalization of $1.96 trillion and...ByInvesting.com', 'May 07, 2025'","May 07, 2025"
27,"'Amazon to Invest $4B+ to Launch Infrastructure Region in ChileAmazon (NASDAQ:AMZN) today announced it plans to launch an Amazon Web Services (AWS) infrastructure Region in Chile by the end of...ByInvesting.com', 'May 07, 2025'","May 07, 2025"
28,"'Cantor downgrades Marvell Technology: Potential catalysts ’few and far between’Investing.com -- Cantor Fitzgerald downgraded Marvell (NASDAQ:MRVL) Technology to Neutral from Overweight in a note Wednesday,...ByInvesting.com', 'May 07, 2025'","May 07, 2025"
29,"'Amazon’s Bezos leads new investment in AI data company TolokaBy Alexander Marrow LONDON (Reuters) -Jeff Bezos’ personal firm Bezos Expeditions is leading a $72-million investment in...ByReuters', 'May 07, 2025'","May 07, 2025"
30,"'Trump’s movie tariff threat alarms India’s film makersBy Haripriya Suresh, Saurabh Sharma and Rishika Sadam BENGALURU/NEW DELHI/HYDERABAD (Reuters) -India’s film industry, which earns...ByReuters', 'May 07, 2025'","May 07, 2025"
31,"'Amazon’s Zoox to scale up robotaxi production in 2026 for US growth- FTInvesting.com-- Amazon.com’s (NASDAQ:AMZN) self-driving start-up, Zoox, will scale up production next year as it proceeds with...ByInvesting.com', 'May 07, 2025'","May 07, 2025"
32,"'Amazon’s Zoox to scale up robotaxi production for US expansion, FT reports(Reuters) -Amazon’s self-driving start-up Zoox will increase production next year as it ramps up plans for a commercial rollout...ByReuters', 'May 07, 2025'","May 07, 2025"
33,"'Coty cuts forecast, delays investor day as economic uncertainty hits US market(Reuters) -CoverGirl-parent Coty (NYSE:COTY) cut fiscal 2025 profit forecast on Tuesday and postponed its investor day by at...ByReuters', 'May 06, 2025'","May 06, 2025"
34,"'Amazon’s robotaxi unit Zoox agrees to software recall after self-driving Las Vegas crashBy David Shepardson WASHINGTON (Reuters) -Amazon.com’s self-driving unit Zoox agreed to recall 270 driverless vehicles after an...ByReuters', 'May 06, 2025'","May 06, 2025"
35,"'Zoox recalls 270 driverless cars following crash in Las VegasInvesting.com -- Amazon.com (NASDAQ:AMZN)’s autonomous vehicle division, Zoox, has decided to recall 270 of its driverless...ByInvesting.com', 'May 06, 2025'","May 06, 2025"
36,"'Amazon’s Zoox recalling self-driving vehicles after crash last month in Las VegasByInvesting.com', 'May 06, 2025'","May 06, 2025"
37,"'Cisco shows quantum networking chip, opens new lab By Stephen Nellis SAN FRANCISCO (Reuters) -Cisco Systems on Tuesday showed a prototype chip for networking quantum computers...ByReuters', 'May 06, 2025'","May 06, 2025"
38,"'Sinclair Broadcas receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 06, 2025'","May 06, 2025"
39,"'Tigress Financial lifts Amazon stock price target to $305On Tuesday, Tigress Financial Partners showed a positive stance on Amazon.com (NASDAQ:AMZN) by raising its 12-month price target...ByInvesting.com', 'May 06, 2025'","May 06, 2025"
40,"'DoorDash, UK’s Deliveroo serve up $3.9 billion deal to take on rivalsBy Pushkala Aripaka and Anuja Bharat Mistry (Reuters) -U.S. meal delivery firm DoorDash (NASDAQ:DASH) will buy Deliveroo...ByReuters', 'May 06, 2025'","May 06, 2025"
41,"'Amazon Com Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 06, 2025'","May 06, 2025"
42,"'Cellebrite Unveils Spring 2025 Release to Accelerate Global InvestigationsAI and Cloud as Strategic Foundations for the Next Era of its Digital Investigation PlatformTYSONS CORNER, Va. and PETAH TIKVA,...ByInvesting.com', 'May 06, 2025'","May 06, 2025"
43,"'Fabrinet receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 06, 2025'","May 06, 2025"
44,"'Morning Bid: Asia FX rattles and Merz stumblesBy Mike Dolan LONDON (Reuters) - A look at what matters in U.S. and global markets today from Mike Dolan, Editor-At-Large,...ByReuters', 'May 06, 2025'","May 06, 2025"
45,"'Fabrinet receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 06, 2025'","May 06, 2025"
46,"'IBM CEO makes play for AI market and more US investment(Reuters) -IBM on Tuesday made a play for more sales in the crowded artificial intelligence field, touting tools that could help...ByReuters', 'May 06, 2025'","May 06, 2025"
47,"'S&P 500 snaps 9-session win streak after latest Trump tariffBy Chuck Mikolajczak NEW YORK (Reuters) -The S&P 500 fell to snap its longest streak of gains in 20 years on Monday as investors...ByReuters', 'May 05, 2025'","May 05, 2025"
48,"'Trump orders 100% tariff on foreign-made movies to save ’dying’ HollywoodBy Andrea Shalal and Tim Reid WASHINGTON (Reuters) -U.S. President Donald Trump on Sunday announced a 100% tariff on movies...ByReuters', 'May 05, 2025', '13'",", 2025', '13"
49,"'Amazon revamps pay structure to favor ’consistently high-performing’ employees - Business InsiderByInvesting.com', 'May 05, 2025'","May 05, 2025"

In [286]:
historical_data['Date'] = pd.to_datetime(historical_data['Date'].str[:10]).dt.strftime('%Y-%m-%d')
historical_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2021-05-10,164.115997,164.149994,159.500000,159.524506,116772000,0.0,0.0
1,2021-05-11,156.813995,161.899994,156.368500,161.195496,92396000,0.0,0.0
2,2021-05-12,159.250000,160.397003,156.654999,157.597000,98728000,0.0,0.0
3,2021-05-13,159.273499,160.192001,156.649994,158.073502,67018000,0.0,0.0
4,2021-05-14,159.278000,161.442993,159.149994,161.145004,66500000,0.0,0.0

In [287]:
pd.set_option('display.max_rows', None)

In [288]:
mask = ~news_articles['article-date'].str.contains(r'\n', regex = True, na = False)
news_articles.loc[mask, 'article-date'] = pd.to_datetime(news_articles.loc[mask, 'article-date'], errors ='coerce').dt.strftime("%Y-%m-%d")

<ipython-input-288-606ec8ebb8a4>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  news_articles.loc[mask, 'article-date'] = pd.to_datetime(news_articles.loc[mask, 'article-date'], errors ='coerce').dt.strftime("%Y-%m-%d")

In [289]:
news_articles['article-title'] = news_articles['article-title'].astype(str)
news_articles['article-title'] = news_articles['article-title'].str.replace('[', '', regex = False).str.replace(']', '', regex = False)
news_articles.head()

,article-title,article-date
0,"'5 big analyst AI moves: Microsoft downgraded; Time to revisit AI trade, WF saysInvesting.com -- Here are the biggest analyst moves in the area of artificial intelligence (AI) for this week. InvestingPro...ByInvesting.com', '5 hours ago'",NaN
1,"'Investing.com’s stocks of the weekInvesting.com -- Market sentiment was given somewhat of a boost this week with the U.S. and U.K. announcing a trade deal...ByInvesting.com', 'May 10, 2025'",2025-05-10
2,"'Eleven soldiers killed in Ecuador after clash with criminal groupQUITO (Reuters) -Eleven soldiers were killed and one was injured in Ecuador’s Amazon (NASDAQ:AMZN) region during an armed...ByReuters', 'May 09, 2025'",2025-05-09
3,"'US Department of Labor closes investigation into Scale AI(Reuters) - The U.S. Department of Labor has closed its investigation into Scale AI’s compliance with the Fair Labor Standards...ByReuters', 'May 09, 2025'",2025-05-09
4,"'Container shipping firms cull Asia-US service as Trump tariffs collapse tradeBy Lisa Baertlein LOS ANGELES (Reuters) -Major container shipping companies are suspending at least six scheduled weekly routes...ByReuters', 'May 09, 2025'",2025-05-09

In [290]:
news_articles['article-date'] = pd.to_datetime(news_articles['article-date'], errors ='coerce').dt.strftime('%Y-%m-%d')
news_articles.head(50)

,article-title,article-date
0,"'5 big analyst AI moves: Microsoft downgraded; Time to revisit AI trade, WF saysInvesting.com -- Here are the biggest analyst moves in the area of artificial intelligence (AI) for this week. InvestingPro...ByInvesting.com', '5 hours ago'",NaN
1,"'Investing.com’s stocks of the weekInvesting.com -- Market sentiment was given somewhat of a boost this week with the U.S. and U.K. announcing a trade deal...ByInvesting.com', 'May 10, 2025'",2025-05-10
2,"'Eleven soldiers killed in Ecuador after clash with criminal groupQUITO (Reuters) -Eleven soldiers were killed and one was injured in Ecuador’s Amazon (NASDAQ:AMZN) region during an armed...ByReuters', 'May 09, 2025'",2025-05-09
3,"'US Department of Labor closes investigation into Scale AI(Reuters) - The U.S. Department of Labor has closed its investigation into Scale AI’s compliance with the Fair Labor Standards...ByReuters', 'May 09, 2025'",2025-05-09
4,"'Container shipping firms cull Asia-US service as Trump tariffs collapse tradeBy Lisa Baertlein LOS ANGELES (Reuters) -Major container shipping companies are suspending at least six scheduled weekly routes...ByReuters', 'May 09, 2025'",2025-05-09
5,"'Brazil, China discuss railway from Peruvian port to Brazil territoryBRASILIA (Reuters) - Brazil is in talks with China to build a railway connecting the Chinese-built mega Chancay port in Peru to...ByReuters', 'May 09, 2025'",2025-05-09
6,"'Morning Bid: Tariff rollback hopes risingBy Mike Dolan LONDON (Reuters) - What matters in U.S. and global markets today By Mike Dolan, Editor-At-Large, Financial Industry...ByReuters', 'May 09, 2025'",2025-05-09
7,"'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'",2025-05-09
8,"'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'",2025-05-09
9,"'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'",2025-05-09
10,"'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'",2025-05-09
11,"'Trade Desk Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 09, 2025'",2025-05-09
12,"'Near-record US container import streak expected to snap in May due to tariffsBy Lisa Baertlein and Andrea Shalal LOS ANGELES/WASHINGTON (Reuters) -U.S. container imports surged in April as companies raced...ByReuters', 'May 08, 2025'",2025-05-08
13,"'Pinterest’s revenue forecast gets boost from AI ad tools, growing marketing spendBy Jaspreet Singh (Reuters) -Pinterest forecast current-quarter revenue above Wall Street estimates on Thursday, signaling its...ByReuters', 'May 08, 2025'",2025-05-08
14,"'Amazon partners with Vetsource to offer pet prescriptionsInvesting.com -- Amazon has expanded its pet care range by partnering with Vetsource, a top pet pharmacy, to provide prescription...ByInvesting.com', 'May 08, 2025'",2025-05-08
15,"'Shopify sees strong revenue as e-commerce business grows despite tariff gloomBy Deborah Mary Sophia (Reuters) - Shopify (NASDAQ:SHOP) is seeing steady growth in the number of merchants signing up on its...ByReuters', 'May 08, 2025'",2025-05-08
16,"'Britain’s digital tax on ’Big Tech’ not impacted by trade dealLONDON (Reuters) -Britain’s digital services tax, imposed on U.S. companies like Amazon (NASDAQ:AMZN), Google (NASDAQ:GOOGL) and...ByReuters', 'May 08, 2025'",2025-05-08
17,"'The Trade Desk Q1 preview: Here’s why RBC Capital Markets analysts are expecting a ‘solid start’ByInvesting.com', 'May 08, 2025'",2025-05-08
18,"'Mega-cap tech names seem to be less impacted by tariffs than S&P peers - JefferiesInvesting.com - Aggressive U.S. tariffs have seemed to hurt the so-called ""Magnificent Seven"" mega-cap tech companies less than...ByInvesting.com', 'May 08, 2025'",2025-05-08
19,"'Carvana receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 08, 2025'",2025-05-08
20,"'Shopify’s Q1 results expected to beat, but trade policy clouds outlookByInvesting.com', 'May 08, 2025'",2025-05-08
21,"'Google cuts about 200 staff in global business unit, The Information reports(Reuters) -Google on Tuesday cut about 200 jobs across its global business unit, which is responsible for sales and partnerships,...ByReuters', 'May 07, 2025'",2025-05-07
22,"'Marvell Technology Group Ltd receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 07, 2025'",2025-05-07
23,"'Amazon’s 800K stake in AMD realted to ZT acqusitionByInvesting.com', 'May 07, 2025'",2025-05-07
24,"'PepsiCo and AWS Collaborate to Accelerate Digital TransformationPepsiCo selects AWS as a strategic cloud provider for AI, supply chain and consumer experience. PURCHASE, N.Y., May 7, 2025...ByInvesting.com', 'May 07, 2025'",2025-05-07
25,"'Amazon to spend $4 billion on cloud infrastructure in ChileBy Fabian Cambero SANTIAGO (Reuters) -Amazon’s cloud computing division will invest $4 billion to build its first data centers...ByReuters', 'May 07, 2025'",2025-05-07
26,"'Amazon to launch AWS region in Chile, investing $4 billionSEATTLE - Amazon.com Inc. (NASDAQ: AMZN), the prominent broadline retail player with a market capitalization of $1.96 trillion and...ByInvesting.com', 'May 07, 2025'",2025-05-07
27,"'Amazon to Invest $4B+ to Launch Infrastructure Region in ChileAmazon (NASDAQ:AMZN) today announced it plans to launch an Amazon Web Services (AWS) infrastructure Region in Chile by the end of...ByInvesting.com', 'May 07, 2025'",2025-05-07
28,"'Cantor downgrades Marvell Technology: Potential catalysts ’few and far between’Investing.com -- Cantor Fitzgerald downgraded Marvell (NASDAQ:MRVL) Technology to Neutral from Overweight in a note Wednesday,...ByInvesting.com', 'May 07, 2025'",2025-05-07
29,"'Amazon’s Bezos leads new investment in AI data company TolokaBy Alexander Marrow LONDON (Reuters) -Jeff Bezos’ personal firm Bezos Expeditions is leading a $72-million investment in...ByReuters', 'May 07, 2025'",2025-05-07
30,"'Trump’s movie tariff threat alarms India’s film makersBy Haripriya Suresh, Saurabh Sharma and Rishika Sadam BENGALURU/NEW DELHI/HYDERABAD (Reuters) -India’s film industry, which earns...ByReuters', 'May 07, 2025'",2025-05-07
31,"'Amazon’s Zoox to scale up robotaxi production in 2026 for US growth- FTInvesting.com-- Amazon.com’s (NASDAQ:AMZN) self-driving start-up, Zoox, will scale up production next year as it proceeds with...ByInvesting.com', 'May 07, 2025'",2025-05-07
32,"'Amazon’s Zoox to scale up robotaxi production for US expansion, FT reports(Reuters) -Amazon’s self-driving start-up Zoox will increase production next year as it ramps up plans for a commercial rollout...ByReuters', 'May 07, 2025'",2025-05-07
33,"'Coty cuts forecast, delays investor day as economic uncertainty hits US market(Reuters) -CoverGirl-parent Coty (NYSE:COTY) cut fiscal 2025 profit forecast on Tuesday and postponed its investor day by at...ByReuters', 'May 06, 2025'",2025-05-06
34,"'Amazon’s robotaxi unit Zoox agrees to software recall after self-driving Las Vegas crashBy David Shepardson WASHINGTON (Reuters) -Amazon.com’s self-driving unit Zoox agreed to recall 270 driverless vehicles after an...ByReuters', 'May 06, 2025'",2025-05-06
35,"'Zoox recalls 270 driverless cars following crash in Las VegasInvesting.com -- Amazon.com (NASDAQ:AMZN)’s autonomous vehicle division, Zoox, has decided to recall 270 of its driverless...ByInvesting.com', 'May 06, 2025'",2025-05-06
36,"'Amazon’s Zoox recalling self-driving vehicles after crash last month in Las VegasByInvesting.com', 'May 06, 2025'",2025-05-06
37,"'Cisco shows quantum networking chip, opens new lab By Stephen Nellis SAN FRANCISCO (Reuters) -Cisco Systems on Tuesday showed a prototype chip for networking quantum computers...ByReuters', 'May 06, 2025'",2025-05-06
38,"'Sinclair Broadcas receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 06, 2025'",2025-05-06
39,"'Tigress Financial lifts Amazon stock price target to $305On Tuesday, Tigress Financial Partners showed a positive stance on Amazon.com (NASDAQ:AMZN) by raising its 12-month price target...ByInvesting.com', 'May 06, 2025'",2025-05-06
40,"'DoorDash, UK’s Deliveroo serve up $3.9 billion deal to take on rivalsBy Pushkala Aripaka and Anuja Bharat Mistry (Reuters) -U.S. meal delivery firm DoorDash (NASDAQ:DASH) will buy Deliveroo...ByReuters', 'May 06, 2025'",2025-05-06
41,"'Amazon Com Inc receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 06, 2025'",2025-05-06
42,"'Cellebrite Unveils Spring 2025 Release to Accelerate Global InvestigationsAI and Cloud as Strategic Foundations for the Next Era of its Digital Investigation PlatformTYSONS CORNER, Va. and PETAH TIKVA,...ByInvesting.com', 'May 06, 2025'",2025-05-06
43,"'Fabrinet receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 06, 2025'",2025-05-06
44,"'Morning Bid: Asia FX rattles and Merz stumblesBy Mike Dolan LONDON (Reuters) - A look at what matters in U.S. and global markets today from Mike Dolan, Editor-At-Large,...ByReuters', 'May 06, 2025'",2025-05-06
45,"'Fabrinet receives Investment Bank Analyst Rating UpdateByInvesting.com', 'May 06, 2025'",2025-05-06
46,"'IBM CEO makes play for AI market and more US investment(Reuters) -IBM on Tuesday made a play for more sales in the crowded artificial intelligence field, touting tools that could help...ByReuters', 'May 06, 2025'",2025-05-06
47,"'S&P 500 snaps 9-session win streak after latest Trump tariffBy Chuck Mikolajczak NEW YORK (Reuters) -The S&P 500 fell to snap its longest streak of gains in 20 years on Monday as investors...ByReuters', 'May 05, 2025'",2025-05-05
48,"'Trump orders 100% tariff on foreign-made movies to save ’dying’ HollywoodBy Andrea Shalal and Tim Reid WASHINGTON (Reuters) -U.S. President Donald Trump on Sunday announced a 100% tariff on movies...ByReuters', 'May 05, 2025', '13'",NaN
49,"'Amazon revamps pay structure to favor ’consistently high-performing’ employees - Business InsiderByInvesting.com', 'May 05, 2025'",2025-05-05

In [291]:
news_articles = news_articles.dropna(subset=['article-date'])
news_articles

Output hidden; open in https://colab.research.google.com to view.

In [292]:
len(news_articles.index)

8964

In [293]:
news_articles_grouped = news_articles.groupby('article-date')['article-title'].apply(list).reset_index()
news_articles_grouped = news_articles_grouped.rename(columns={"article-date":'Date'})
news_articles_grouped.head(10)

,Date,article-title
0,2021-05-10,"['Formula One great to develop electric vans, SUVs for carmakers, startupsBy Nick Carey LONDON (Reuters) - Supercar maker the Gordon Murray Group said on Tuesday it plans a 300-million-pound ($420...ByReuters', 'May 10, 2021', 'Amazon raises $1 billion sustainable bond for climate, social causesBy Kate Duguid and Simon Jessop NEW YORK/LONDON (Reuters) - Amazon.com Inc (NASDAQ:AMZN) issued its first sustainability bond on...ByReuters', 'May 10, 2021', 'The great tech exodus: The Ethereum blockchain is the new San FranciscoRemember the “Silicon Valley Tech Bubble”? In the early- to mid-2000s, the San Francisco Bay Area gave birth to some...ByCointelegraph', 'May 10, 2021', 'Should You Buy the Dip in Jumia Technologies?Based in Germany, Jumia (JMIA) is the top e-commerce platform in Africa. Even though the stock has declined over the past few...ByStockNews', 'May 10, 2021']"
1,2021-05-11,"['Washington Post names Sally Buzbee first woman to lead newsroomBy Helen Coster (Reuters) -The Washington Post named Sally Buzbee executive editor on Tuesday, effective June 1, making her the...ByReuters', 'May 11, 2021', 'Barry Jenkins says he feared making slavery drama \'The Underground Railroad\'By Lisa Keddie LONDON (Reuters) - ""Moonlight"" director Barry Jenkins switches to the small screen for an adaptation of the...ByReuters', 'May 11, 2021', 'S&P 500 Off Lows as Traders Snap Up Battered Tech StocksBy Yasin Ebrahim Investing.com – The S&P 500 reversed some losses Tuesday as investors appeared to buy the dip in tech, though...ByInvesting.com', 'May 11, 2021', ""Tech giants join call for funding U.S. chip productionBy Stephen Nellis (Reuters) - Some of the world's biggest chip buyers, including Apple Inc (NASDAQ:AAPL), Microsoft Corp...ByReuters"", 'May 11, 2021', 'FAANG Slips On Fear Of Money Tightening, Regulatory Action To Tame Big TechBy Dhirendra Tripathi Investing.com – ..."
2,2021-05-12,"['Sonos boosts sales outlook despite global chip shortage, shares riseBy Stephen Nellis (Reuters) -Connected speaker maker Sonos (NASDAQ:SONO) Inc on Wednesday raised its annual sales forecast above...ByReuters', 'May 12, 2021', 'Hedge funds bet on subscription-based businesses, pharmacy and copperBy Maiya Keidan (Reuters) - Hedge fund managers on Wednesday recommended buying stocks of companies they believe will benefit...ByReuters', 'May 12, 2021', 'White House labor task force holds first meeting to help more workers join unionsBy Nandita Bose WASHINGTON (Reuters) -The White House labor task force, headed by Vice President Kamala Harris, is set to meet...ByReuters', 'May 12, 2021', ""Americans' top financial regret? Not saving for an emergencyBy Chris Taylor NEW YORK (Reuters) - Regrets, we've had a few. Or when it comes to our money, a whole lot. In fact, more than 80%...ByReuters"", 'May 12, 2021', 'Amazon wins $303 million court fight in blow to EU tax crusadeBy Foo Yun Chee B..."
3,2021-05-13,"['Amazon seeks renewable power for Japan data centres - NikkeiTOKYO (Reuters) - Amazon.com Inc (NASDAQ:AMZN) is in talks with Japanese power utilities and trading houses to build a renewable...ByReuters', 'May 13, 2021', 'White House group gets to work on plan to increase unionization of U.S. workersBy Steve Holland and Nandita Bose WASHINGTON (Reuters) -The White House on Thursday launched an effort to increase the number of...ByReuters', 'May 13, 2021', ""Amazon to hire 75,000 workers, offers $100 extra for vaccination proof(Reuters) - Amazon.com Inc (NASDAQ:AMZN) will give $100 more to new hires with proof of COVID-19 vaccination, the world's largest...ByReuters"", 'May 13, 2021', ""Google wins cloud deal from SpaceX for Starlink internet service(Reuters) - Google (NASDAQ:GOOGL) has won a deal to provide cloud services to Elon Musk's SpaceX, which has launched a slew of...ByReuters"", 'May 13, 2021', ""Canada's Cargojet tells pilots it may shift some work to U.S.By Allison Lampert (..."
4,2021-05-14,"['Less than 3% of U.S. small businesses could face tax hikes under Biden plan -White HouseBy Nandita Bose WASHINGTON (Reuters) -Less than 3% of the roughly 30 million small-business owners in the United States could...ByReuters', 'May 14, 2021', 'Retailers set for earnings stage after inflation-sparked market turbulenceBy Lewis Krauskopf NEW YORK (Reuters) - Earnings reports from major retailers will be in focus next week after the U.S. stock...ByReuters', 'May 14, 2021', 'S&P 500 Racks Up Gains as Tech Turnaround Continues After Recent RoutBy Yasin Ebrahim Investing.com – The S&P 500 rose Friday, as tech continued its recovery following a recent rout, while cyclicals...ByInvesting.com', 'May 14, 2021', 'Disney, Airbnb Fall Premarket; DoorDash, Snowflake RiseBy Peter Nurse Investing.com -- Stocks in focus in premarket trade on Friday, May 14th. Please refresh for updates. Disney...ByInvesting.com', 'May 14, 2021', ""Google leads U.S. business push to preserve work permits for H-1B..."
5,2021-05-17,"['EU eyes another go at more unified European business taxationBy Jan Strupczewski BRUSSELS (Reuters) - The European Commission wants to propose in 2023 a more unified way of taxing companies...ByReuters', 'May 17, 2021', 'How a golf tournament led to the merger of Discovery, WarnerMediaBy Krystal Hu and Kenneth Li (Reuters) -It all started with two friends commiserating. Discovery (NASDAQ:DISCA) Inc CEO David...ByReuters', 'May 17, 2021', ""Parler returns to Apple's App Store, names new CEOBy Elizabeth Culliford (Reuters) -Parler, a social media app popular with U.S. conservatives, returned to Apple Inc...ByReuters"", 'May 17, 2021', 'U.S., Canadian trade chiefs air concerns ahead of USMCA trade deal meetingBy David Lawder WASHINGTON (Reuters) -U.S. Trade Representative Katherine Tai discussed a range of trade issues with Canadian...ByReuters', 'May 17, 2021', 'Some big U.S. hedge funds loaded up on SPACS, value stocks during first quarterBy David Randall NEW YORK (Reuters) - A num..."
6,2021-05-18,"['Amazon extends moratorium on police use of facial recognition softwareBy Jeffrey Dastin (Reuters) -Amazon.com Inc said on Tuesday it is extending until further notice a moratorium it imposed last...ByReuters', 'May 18, 2021', 'Retail Reports, Fed Minutes, NYC Welcomes You: 3 Things to WatchBy Christiana Sciaudone Investing.com -- Markets were up, markets were down, apparently a bit uncertain of where to go. Tech...ByInvesting.com', 'May 18, 2021', 'S&P 500 Slips as Tech Cuts Gains, Energy Loses PowerBy Yasin Ebrahim Investing.com – The S&P 500 slipped Tuesday as tech stocks gave up gains and energy stocks fell sharply amid...ByInvesting.com', 'May 18, 2021', ""Pent-up demand, stimulus power Walmart's 'optimism' for the yearBy Aishwarya Venugopal and Richa Naidu (Reuters) -Walmart Inc on Tuesday raised its full-year earnings forecast after shoppers...ByReuters"", 'May 18, 2021', 'Bank of America to raise U.S. minimum hourly wage to $25 by 2025By Noor Zainab Hussain (Reuters) -Bank..."
7,2021-05-19,"['Amazon.com faces five new racial, gender bias lawsuitsBy Jonathan Stempel (Reuters) - Amazon.com Inc (NASDAQ:AMZN) was hit on Wednesday with five new lawsuits by women who worked in...ByReuters', 'May 19, 2021', 'Echoing Amazon: Walmart, Target try local package deliveryBy Lisa Baertlein LOS ANGELES (Reuters) -Walmart and Target are testing their own home package delivery services in the United...ByReuters', 'May 19, 2021', ""Twitter finds its AI tends to crop out Black people, men from photosBy Paresh Dave (Reuters) - Twitter Inc (NYSE:TWTR)'s image-cropping algorithm has a problematic bias toward excluding Black...ByReuters"", 'May 19, 2021', 'FAANG Stocks Slip Amid Worries Over Cryptos, Commodities, InflationBy Dhirendra Tripathi Investing.com – The FAANG pack fell in Wednesday’s premarket as concerns over inflation, regulation of...ByInvesting.com', 'May 19, 2021', ""Study finds Asians largely 'invisible' in Hollywood's top films(Adds Smith's full name and title paragraph 10) B..."
8,2021-05-20,"['S&P 500 Snaps 3-Day Losing Streak as Tech Reigns SupremeBy Yasin Ebrahim Investing.com – The S&P 500 closed higher Thursday, snapping a three-day losing streak as a rally in chips and...ByInvesting.com', 'May 20, 2021', 'ViacomCBS Rallies on Double Upgrade as Consolidation EyedBy Christiana Sciaudone Investing.com -- ViacomCBS (NASDAQ:VIAC) rose more than 4% after getting a double upgrade from Bank of...ByInvesting.com', 'May 20, 2021', 'JPMorgan Chase launches new healthcare-focused unit for U.S. employees(Reuters) - JPMorgan Chase & Co (NYSE:JPM) said on Thursday it launched a unit aimed at improving healthcare for its U.S....ByReuters', 'May 20, 2021', 'Every second counts as startups race to deliver fresh foodBy Kate Holton, James Davey and Douglas Busvine LONDON (Reuters) - In a railway arch in south London, pickers and packers are in...ByReuters', 'May 20, 2021', 'Lockdown shopping hoists Royal Mail profits, outlook uncertainBy Yadarisa Shabong (Reuters) -Royal Mail said c..."
9,2021-05-21,"['U.S. investors look to Europe for next leg of stock gainsBy Lewis Krauskopf NEW YORK (Reuters) - As U.S. stocks are hit with a bout of volatility, some investors are looking to European...ByReuters', 'May 21, 2021', 'S&P 500 Falls for Second Week as Tech StuttersBy Yasin Ebrahim Investing.com – The S&P 500 fell for the second week in a row Friday as the rotation from growth to value...ByInvesting.com', 'May 21, 2021', 'Target vs. BJ Wholesale: Which Retail Stock is a Better Buy?The retail market is changing rapidly with Amazon (NASDAQ:AMZN) and other major e-commerce players increasingly grabbing customers...ByStockNews', 'May 21, 2021', 'S&P in Choppy Trade as Tech Sluggish Amid Rotation From Growth to ValueBy Yasin Ebrahim Investing.com – The S&P 500 struggled for direction Friday as the rotation from growth to value continued,...ByInvesting.com', 'May 21, 2021', 'BMO investment arm sold Microsoft over U.S. Army headset dealBy Ross Kerber BOSTON (Reuters) - A responsible-inves..."

In [294]:
final_data = pd.merge(historical_data, news_articles_grouped,on="Date", how='inner')
final_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,article-title
0,2021-05-10,164.115997,164.149994,159.500000,159.524506,116772000,0.0,0.0,"['Formula One great to develop electric vans, SUVs for carmakers, startupsBy Nick Carey LONDON (Reuters) - Supercar maker the Gordon Murray Group said on Tuesday it plans a 300-million-pound ($420...ByReuters', 'May 10, 2021', 'Amazon raises $1 billion sustainable bond for climate, social causesBy Kate Duguid and Simon Jessop NEW YORK/LONDON (Reuters) - Amazon.com Inc (NASDAQ:AMZN) issued its first sustainability bond on...ByReuters', 'May 10, 2021', 'The great tech exodus: The Ethereum blockchain is the new San FranciscoRemember the “Silicon Valley Tech Bubble”? In the early- to mid-2000s, the San Francisco Bay Area gave birth to some...ByCointelegraph', 'May 10, 2021', 'Should You Buy the Dip in Jumia Technologies?Based in Germany, Jumia (JMIA) is the top e-commerce platform in Africa. Even though the stock has declined over the past few...ByStockNews', 'May 10, 2021']"
1,2021-05-11,156.813995,161.899994,156.368500,161.195496,92396000,0.0,0.0,"['Washington Post names Sally Buzbee first woman to lead newsroomBy Helen Coster (Reuters) -The Washington Post named Sally Buzbee executive editor on Tuesday, effective June 1, making her the...ByReuters', 'May 11, 2021', 'Barry Jenkins says he feared making slavery drama \'The Underground Railroad\'By Lisa Keddie LONDON (Reuters) - ""Moonlight"" director Barry Jenkins switches to the small screen for an adaptation of the...ByReuters', 'May 11, 2021', 'S&P 500 Off Lows as Traders Snap Up Battered Tech StocksBy Yasin Ebrahim Investing.com – The S&P 500 reversed some losses Tuesday as investors appeared to buy the dip in tech, though...ByInvesting.com', 'May 11, 2021', ""Tech giants join call for funding U.S. chip productionBy Stephen Nellis (Reuters) - Some of the world's biggest chip buyers, including Apple Inc (NASDAQ:AAPL), Microsoft Corp...ByReuters"", 'May 11, 2021', 'FAANG Slips On Fear Of Money Tightening, Regulatory Action To Tame Big TechBy Dhirendra Tripathi Investing.com – ..."
2,2021-05-12,159.250000,160.397003,156.654999,157.597000,98728000,0.0,0.0,"['Sonos boosts sales outlook despite global chip shortage, shares riseBy Stephen Nellis (Reuters) -Connected speaker maker Sonos (NASDAQ:SONO) Inc on Wednesday raised its annual sales forecast above...ByReuters', 'May 12, 2021', 'Hedge funds bet on subscription-based businesses, pharmacy and copperBy Maiya Keidan (Reuters) - Hedge fund managers on Wednesday recommended buying stocks of companies they believe will benefit...ByReuters', 'May 12, 2021', 'White House labor task force holds first meeting to help more workers join unionsBy Nandita Bose WASHINGTON (Reuters) -The White House labor task force, headed by Vice President Kamala Harris, is set to meet...ByReuters', 'May 12, 2021', ""Americans' top financial regret? Not saving for an emergencyBy Chris Taylor NEW YORK (Reuters) - Regrets, we've had a few. Or when it comes to our money, a whole lot. In fact, more than 80%...ByReuters"", 'May 12, 2021', 'Amazon wins $303 million court fight in blow to EU tax crusadeBy Foo Yun Chee B..."
3,2021-05-13,159.273499,160.192001,156.649994,158.073502,67018000,0.0,0.0,"['Amazon seeks renewable power for Japan data centres - NikkeiTOKYO (Reuters) - Amazon.com Inc (NASDAQ:AMZN) is in talks with Japanese power utilities and trading houses to build a renewable...ByReuters', 'May 13, 2021', 'White House group gets to work on plan to increase unionization of U.S. workersBy Steve Holland and Nandita Bose WASHINGTON (Reuters) -The White House on Thursday launched an effort to increase the number of...ByReuters', 'May 13, 2021', ""Amazon to hire 75,000 workers, offers $100 extra for vaccination proof(Reuters) - Amazon.com Inc (NASDAQ:AMZN) will give $100 more to new hires with proof of COVID-19 vaccination, the world's largest...ByReuters"", 'May 13, 2021', ""Google wins cloud deal from SpaceX for Starlink internet service(Reuters) - Google (NASDAQ:GOOGL) has won a deal to provide cloud services to Elon Musk's SpaceX, which has launched a slew of...ByReuters"", 'May 13, 2021', ""Canada's Cargojet tells pilots it may shift some work to U.S.By Allison Lampert (..."
4,2021-05-14,159.278000,161.442993,159.149994,161.145004,66500000,0.0,0.0,"['Less than 3% of U.S. small businesses could face tax hikes under Biden plan -White HouseBy Nandita Bose WASHINGTON (Reuters) -Less than 3% of the roughly 30 million small-business owners in the United States could...ByReuters', 'May 14, 2021', 'Retailers set for earnings stage after inflation-sparked market turbulenceBy Lewis Krauskopf NEW YORK (Reuters) - Earnings reports from major retailers will be in focus next week after the U.S. stock...ByReuters', 'May 14, 2021', 'S&P 500 Racks Up Gains as Tech Turnaround Continues After Recent RoutBy Yasin Ebrahim Investing.com – The S&P 500 rose Friday, as tech continued its recovery following a recent rout, while cyclicals...ByInvesting.com', 'May 14, 2021', 'Disney, Airbnb Fall Premarket; DoorDash, Snowflake RiseBy Peter Nurse Investing.com -- Stocks in focus in premarket trade on Friday, May 14th. Please refresh for updates. Disney...ByInvesting.com', 'May 14, 2021', ""Google leads U.S. business push to preserve work permits for H-1B..."

In [295]:
print(len(final_data))

982

In [297]:
final_data['article-title'] = final_data['article-title'].astype(str)
final_data['article-title'] = final_data['article-title'].str.replace('[','', regex = False).str.replace(']','' ,regex = False)
final_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits,article-title
0,2021-05-10,164.115997,164.149994,159.500000,159.524506,116772000,0.0,0.0,"""'Formula One great to develop electric vans, SUVs for carmakers, startupsBy Nick Carey LONDON (Reuters) - Supercar maker the Gordon Murray Group said on Tuesday it plans a 300-million-pound ($420...ByReuters', 'May 10, 2021'"", ""'Amazon raises $1 billion sustainable bond for climate, social causesBy Kate Duguid and Simon Jessop NEW YORK/LONDON (Reuters) - Amazon.com Inc (NASDAQ:AMZN) issued its first sustainability bond on...ByReuters', 'May 10, 2021'"", ""'The great tech exodus: The Ethereum blockchain is the new San FranciscoRemember the “Silicon Valley Tech Bubble”? In the early- to mid-2000s, the San Francisco Bay Area gave birth to some...ByCointelegraph', 'May 10, 2021'"", ""'Should You Buy the Dip in Jumia Technologies?Based in Germany, Jumia (JMIA) is the top e-commerce platform in Africa. Even though the stock has declined over the past few...ByStockNews', 'May 10, 2021'"""
1,2021-05-11,156.813995,161.899994,156.368500,161.195496,92396000,0.0,0.0,"""'Washington Post names Sally Buzbee first woman to lead newsroomBy Helen Coster (Reuters) -The Washington Post named Sally Buzbee executive editor on Tuesday, effective June 1, making her the...ByReuters', 'May 11, 2021'"", '\'Barry Jenkins says he feared making slavery drama \\\'The Underground Railroad\\\'By Lisa Keddie LONDON (Reuters) - ""Moonlight"" director Barry Jenkins switches to the small screen for an adaptation of the...ByReuters\', \'May 11, 2021\'', ""'S&P 500 Off Lows as Traders Snap Up Battered Tech StocksBy Yasin Ebrahim Investing.com – The S&P 500 reversed some losses Tuesday as investors appeared to buy the dip in tech, though...ByInvesting.com', 'May 11, 2021'"", '""Tech giants join call for funding U.S. chip productionBy Stephen Nellis (Reuters) - Some of the world\'s biggest chip buyers, including Apple Inc (NASDAQ:AAPL), Microsoft Corp...ByReuters"", \'May 11, 2021\'', ""'FAANG Slips On Fear Of Money Tightening, Regulatory Action To Tame Big TechBy Dhirendra Tripat..."
2,2021-05-12,159.250000,160.397003,156.654999,157.597000,98728000,0.0,0.0,"""'Sonos boosts sales outlook despite global chip shortage, shares riseBy Stephen Nellis (Reuters) -Connected speaker maker Sonos (NASDAQ:SONO) Inc on Wednesday raised its annual sales forecast above...ByReuters', 'May 12, 2021'"", ""'Hedge funds bet on subscription-based businesses, pharmacy and copperBy Maiya Keidan (Reuters) - Hedge fund managers on Wednesday recommended buying stocks of companies they believe will benefit...ByReuters', 'May 12, 2021'"", ""'White House labor task force holds first meeting to help more workers join unionsBy Nandita Bose WASHINGTON (Reuters) -The White House labor task force, headed by Vice President Kamala Harris, is set to meet...ByReuters', 'May 12, 2021'"", '""Americans\' top financial regret? Not saving for an emergencyBy Chris Taylor NEW YORK (Reuters) - Regrets, we\'ve had a few. Or when it comes to our money, a whole lot. In fact, more than 80%...ByReuters"", \'May 12, 2021\'', ""'Amazon wins $303 million court fight in blow to EU tax crusadeBy Fo..."
3,2021-05-13,159.273499,160.192001,156.649994,158.073502,67018000,0.0,0.0,"""'Amazon seeks renewable power for Japan data centres - NikkeiTOKYO (Reuters) - Amazon.com Inc (NASDAQ:AMZN) is in talks with Japanese power utilities and trading houses to build a renewable...ByReuters', 'May 13, 2021'"", ""'White House group gets to work on plan to increase unionization of U.S. workersBy Steve Holland and Nandita Bose WASHINGTON (Reuters) -The White House on Thursday launched an effort to increase the number of...ByReuters', 'May 13, 2021'"", '""Amazon to hire 75,000 workers, offers $100 extra for vaccination proof(Reuters) - Amazon.com Inc (NASDAQ:AMZN) will give $100 more to new hires with proof of COVID-19 vaccination, the world\'s largest...ByReuters"", \'May 13, 2021\'', '""Google wins cloud deal from SpaceX for Starlink internet service(Reuters) - Google (NASDAQ:GOOGL) has won a deal to provide cloud services to Elon Musk\'s SpaceX, which has launched a slew of...ByReuters"", \'May 13, 2021\'', '""Canada\'s Cargojet tells pilots it may shift some work to U.S.By Al..."
4,2021-05-14,159.278000,161.442993,159.149994,161.145004,66500000,0.0,0.0,"""'Less than 3% of U.S. small businesses could face tax hikes under Biden plan -White HouseBy Nandita Bose WASHINGTON (Reuters) -Less than 3% of the roughly 30 million small-business owners in the United States could...ByReuters', 'May 14, 2021'"", ""'Retailers set for earnings stage after inflation-sparked market turbulenceBy Lewis Krauskopf NEW YORK (Reuters) - Earnings reports from major retailers will be in focus next week after the U.S. stock...ByReuters', 'May 14, 2021'"", ""'S&P 500 Racks Up Gains as Tech Turnaround Continues After Recent RoutBy Yasin Ebrahim Investing.com – The S&P 500 rose Friday, as tech continued its recovery following a recent rout, while cyclicals...ByInvesting.com', 'May 14, 2021'"", ""'Disney, Airbnb Fall Premarket; DoorDash, Snowflake RiseBy Peter Nurse Investing.com -- Stocks in focus in premarket trade on Friday, May 14th. Please refresh for updates. Disney...ByInvesting.com', 'May 14, 2021'"", '""Google leads U.S. business push to preserve work permits ..."

In [300]:
final_data.to_csv('AMZN_DATA_WITH_NEWS_NO_SENTIMENT.csv',index = False)